### Numpy

In [1]:
import numpy as np

### Vectors

In [4]:
# creating an array from a list

arr = np.array([1, 2, 3])

type(arr)

numpy.ndarray

In [8]:
# the list can include other types of data like floats and strings:

arr_strings = np.array(["a", "b", "f"])
arr_floats = np.array([8.3, 4.1, 5.4])

In [9]:
arr_strings

array(['a', 'b', 'f'], dtype='<U1')

In [10]:
arr_floats

array([8.3, 4.1, 5.4])

In [33]:
# getting elements from the vector
arr_floats[1]

4.1

In [34]:
# slicing a vector
# like slicing a list

arr_floats[1:]

array([4.1, 5.4])

In [35]:
arr_floats[:-1]

array([8.3, 4.1])

In [11]:
# properties of the array

arr.shape

(3,)

In [13]:
n_elements = arr.shape[0]
n_elements

3

In [14]:
# other functions to create arrays

np.zeros((5, ))

array([0., 0., 0., 0., 0.])

In [15]:
np.ones((4, ))

array([1., 1., 1., 1.])

In [16]:
np.full((5, ), "hi!")

array(['hi!', 'hi!', 'hi!', 'hi!', 'hi!'], dtype='<U3')

### Matrices

In [22]:
mtx = np.array([[1, 2], [3, 4]])

mtx

array([[1, 2],
       [3, 4]])

In [23]:
mtx.shape

(2, 2)

In [27]:
# slicing with coordinates
mtx[0, 1]  # zero based index!!

2

In [40]:
# slicing on each dimension
mtx = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

mtx[1:, :-1]

array([[4, 5],
       [7, 8]])

In [41]:
# rank: number of dimensions of an array

np.linalg.matrix_rank(mtx)

2

In [42]:
# we can also obtain the rank of an array from its shape

len(mtx.shape)

2

In [57]:
# creating randomized arrays
# 

a = np.random.rand(3, 3)
a

array([[0.41514353, 0.88702824, 0.52630601],
       [0.37627235, 0.86635828, 0.82201739],
       [0.07746431, 0.26817412, 0.19604112]])

In [58]:
a[1, 1]

0.8663582839378154

In [ ]:
# mutating elements of an array

In [61]:
a[0, 2] = 1
a

array([[0.41514353, 0.88702824, 1.        ],
       [0.37627235, 0.86635828, 0.82201739],
       [0.07746431, 0.26817412, 0.19604112]])